apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: story-label
  template:
    metadata:
      labels:
        app: story-label
    spec:
      containers:
        - name: story-volume
          image: akash290698/kub-data-vol:v1.2
          volumeMounts:
            - mountPath: /app/story
              name: empty-volume
      volumes:
        - name: empty-volume
          emptyDir: {}