apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story-node
  template:
    metadata:
      labels:
        app: story-node
    spec:
      containers:
        - name: story-dep
          image: akash290698/kub-data-vol:v1.1.2
          # volumeMounts:
          #   - mountPath: /app/story
          #     name: story-volume
          volumeMounts:
            - mountPath: /app/story
              name: story-host
      # volumes:
      #   - name: story-volume
      #     emptyDir: {}
      volumes:
        - name: story-host
          hostPath:
            path: /data
            type: DirectoryOrCreate