apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-host
spec:
  replicas: 2
  selector:
    matchLabels:
      app: host
  template:
    metadata:
      labels:
        app: host
    spec:
      containers:
        - name: story-host-volume
          image: akash290698/kub-data-vol:v1.2
          volumeMounts:
            - mountPath: /app/story
              name: host-path-volume
      volumes:
        - name: host-path-volume
          hostPath:
            path: /data
            type: DirectoryOrCreate